# Generated by Django 6.0.5 on 2026-08-31 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(db_index=True, verbose_name='所属课程 ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(verbose_name='作业描述')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='assignment_refs/', verbose_name='参考文档')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'assignments',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField(db_index=True, verbose_name='提交学生用户 ID')),
                ('code', models.TextField(verbose_name='提交的代码')),
                ('status', models.CharField(choices=[('pending', '待评分'), ('graded', '已评分')], default='pending', max_length=20, verbose_name='评分状态')),
                ('score', models.IntegerField(default=0, verbose_name='得分 (0-100)')),
                ('output', models.TextField(blank=True, verbose_name='教师评语')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='作业')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
