# Generated by Django 6.0.6 on 2026-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_refs/', verbose_name='参考文档'),
        ),
    ]
