# Generated by Django 6.0.6 on 2026-08-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_assignment_reference_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='test_cases',
        ),
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, verbose_name='教师评语'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', '待评分'), ('graded', '已评分')], default='pending', max_length=20, verbose_name='评分状态'),
        ),
    ]
