# Generated by Django 6.0.6 on 2026-08-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_email_verification_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='email_verif_email_1b7c61_idx',
            old_name='email_verif_email_created_idx',
        ),
    ]
